<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="Charles" name="ranzhi.System" tests="11" failures="0" timestamp="19 十二月 2017 08:02:15 GMT" time="0.000" errors="1">
  <testcase name="backups" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- backups -->
  <testcase name="TestsendEmail" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- TestsendEmail -->
  <testcase name="ClosePlantask" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- ClosePlantask -->
  <testcase name="LAplantask" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- LAplantask -->
  <testcase name="xuanxuanKey" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- xuanxuanKey -->
  <testcase name="GetInBackStage" time="0.000" classname="ranzhi.System">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at ranzhi.System.GetInBackStage(System.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- GetInBackStage -->
  <testcase name="EditsendEmail" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- EditsendEmail -->
  <testcase name="recyclebin" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- recyclebin -->
  <testcase name="sendEmail" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- sendEmail -->
  <testcase name="DeleteBackups" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- DeleteBackups -->
  <testcase name="RestoreBackups" time="0.000" classname="ranzhi.System">
    <skipped/>
  </testcase> <!-- RestoreBackups -->
</testsuite> <!-- ranzhi.System -->
